name:                ghcid-nvim-simple
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - nvim-hs >= 1.0.0.0
    - nvim-hs-contrib >= 1.0.0.0
    - rio
    - ghcid
    - lens
    - Cabal >= 2.0.0.0
    - filepath
    - directory
    - bytestring
    - containers
    - exceptions
    - unliftio
    - extra
    - stm
    - mtl
