name:                ghcid-nvim-simple
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

executables:
  ghcid-nvim-simple:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - nvim-hs
    - ghcid-nvim-simple

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - nvim-hs >= 1.0.0.0
    - nvim-hs-contrib >= 1.0.0.0
    - rio
    - ghcid
    - lens
    - Cabal >= 2.0.0.0
    - filepath
    - directory
    - bytestring
    - containers
    - exceptions
    - unliftio
    - extra
    - stm
    - mtl
